tko changes
atomiklabs/deploycontracts.io pull request #11
Opened 2022-04-27 08:28 UTC by SzymonGos

2022-04-28 05:27 UTC, korzewski commented on components/steps/icons.tsx
> +export function useStepIcon(currentStepIdx: number, activeStepIdx: number): UseStepIconResult {
Please move this function to the top, or move those svg paths to separate file so this logic is readable

2022-04-28 05:28 UTC, korzewski commented
Please make sure that you read and understand all those comments https://github.com/SzymonGos/deploycontracts.io/pull/3.

If you have any questions please let me know so we can discuss.

2022-04-29 08:36 UTC, korzewski requested changes

2022-04-29 08:36 UTC, korzewski commented on components/steps/Steps.tsx
> +const ReactTooltip = dynamic(() => import('react-tooltip'), {
Why dynamic import here?

2022-04-29 08:36 UTC, korzewski commented on components/steps/Steps.tsx
> +                data-for='custom-class'
Please rename to `step-icon-${idx}`, and the same on ReactTooltip

2022-04-29 08:36 UTC, korzewski commented on components/steps/Steps.tsx
> +          activeStep === idx ? (
This condition can be used to customise particular props of components instead. As most of the result is the same, so code is now repeatable.

2022-04-29 08:36 UTC, korzewski commented on components/steps/index.ts
> +export * from './Steps'
I think we can simply move all the Steps.tsx content here

2022-04-29 08:36 UTC, korzewski commented on pages/tokenDetails.tsx
> +    <section className='pt-20'>
Why padding instead of margin?

2022-04-29 08:36 UTC, korzewski commented on components/steps/useStepIcon.tsx
> +    }
Final rendered icons doesn't look like on the designs. This method is probably overcomplicated. Please try to fix that, but if not possible with this approach, please simply use separate images to achieve good look of the icons.

2022-04-29 08:36 UTC, korzewski commented on styles/utilities.scss
> +.custom-tooltip {
Please rename to `steps-tooltip`, as we may have more variants of the tooltips in the future

2022-04-29 15:14 UTC, SzymonGos commented on components/steps/Steps.tsx
> +const ReactTooltip = dynamic(() => import('react-tooltip'), {
<img width="375" alt="image" src="https://user-images.githubusercontent.com/37188746/165969969-8b951edd-245d-44ba-a3db-0767e836f3af.png">

ReactTooltip has a problem with server-side rendering, so that's the solution I've found. There's another one:
https://stackoverflow.com/questions/64079321/react-tooltip-and-next-js-ssr-issue

let me know what you think. Otherwise, I'll look for another tooltip solution

2022-04-29 19:08 UTC, korzewski commented on components/steps/Steps.tsx
> +const ReactTooltip = dynamic(() => import('react-tooltip'), {
Ok, you can leave dynamic for now

2022-04-29 19:32 UTC, korzewski requested changes

2022-04-29 19:32 UTC, korzewski commented on components/steps/index.tsx
> +const pageTitles = ['Token Details', 'Token Allocation', 'Marketing details', 'Summary']
Please rename to stepTitles

2022-04-29 19:32 UTC, korzewski commented on components/steps/index.tsx
> +        {[Step1Icon, Step2Icon, Step3Icon, Step4Icon].map((StepIcon, idx) => (
You do not need now those `Step1Icon`, `Step2Icon` etc.
Please replace with `[...Array(4)].map((_, idx) =>`

2022-04-29 19:32 UTC, korzewski commented on components/steps/icons.tsx
> +export function Step1Icon(props: any) {
All 4 functions are now the same, please remove them all.
You can use this <img> tag directly inside a map

2022-05-05 09:43 UTC, korzewski approved these changes
Just minor suggestions. Please fix conflicts and merge

2022-05-05 09:43 UTC, korzewski commented on components/steps/index.tsx
> +                STEP {activeStep + 1}/4
You can improve this by replacing `4` with `stepTitles.length`. Then when you add or remove step this would be aligned - but it's minor

2022-05-05 09:43 UTC, korzewski commented on pages/tokenDetails.tsx
> +    <section className='pt-20'>
Just a reminder for this question?

2022-05-05 13:24 UTC, merged