Token allocation page allocation cart
atomiklabs/deploycontracts.io pull request #13
Opened 2022-04-28 18:36 UTC by SzymonGos

2022-04-28 18:56 UTC, SzymonGos commented
As we discussed: I left the delete option unable for the first allocationCard. In my opinion, this will lead to a good UX.

2022-04-29 09:15 UTC, korzewski requested changes
I assume the logic would come later, so not checking it now

2022-04-29 09:15 UTC, korzewski commented on pages/tokenAllocation.tsx
> +    setCounter((prev) => (prev === 14 ? 0 : prev + 1))
Import this array `colourPallete` and write it like this

`prev === colourPallete.length`? 0 : prev + 1

2022-04-29 09:15 UTC, korzewski commented on pages/tokenAllocation.tsx
> +  const [counter, setCounter] = useState(0)
Not sure why you need this counter for?

2022-04-29 09:15 UTC, korzewski commented on pages/tokenAllocation.tsx
> +  function deleteAllocation(index: number) {
Please create token context and move this logic to separate file. Then you could get all the logic via 
```const {allocations, addAllocation, removeAllocation} = useToken()```

Same as useCart logic from the other project we've been doing

2022-04-29 09:15 UTC, korzewski commented on styles/index.scss
>  .body-gradient {
Can we have empty line between new css classes?

2022-04-29 09:15 UTC, korzewski commented on components/Delete.tsx
> +export default function Delete(props: React.SVGProps<SVGSVGElement>) {
Hover state doesn't look like the one on the designs

2022-04-30 19:26 UTC, SzymonGos commented on components/AllocationCard.tsx
> +      {myKey === 0 ? null : (
I don't get why I should swap to boolean. In the end, I must use some kind of statement to verify which card is index === 0.

2022-04-30 19:57 UTC, SzymonGos commented
FYI: I added useLocalStorage, however, during implementation I was receiving an error: 'Hydration failed because the initial UI does not match what was rendered on the server'. Right now is disabled, as this can be resolved later and I don't want to be stuck here.

2022-05-01 09:47 UTC, tk-o commented
> FYI: I added useLocalStorage, however, during implementation I was receiving an error: 'Hydration failed because the initial UI does not match what was rendered on the server'. Right now is disabled, as this can be resolved later and I don't want to be stuck here.

This issue happens as localStorage is client-side only API. If you want to avoid hydration issues, you can use cookies (as they can be accessed on both, server-side, and client-side).

2022-05-05 13:54 UTC, korzewski approved these changes
Just minor comment, please merge after that

2022-05-05 13:54 UTC, korzewski commented on components/AllocationCard.tsx
> +      {index && (
This line would print `0` on the first item. Please replace it with `!!index`

2022-05-05 14:02 UTC, merged