Navbar
atomiklabs/deploycontracts.io pull request #29
Opened 2022-06-01 17:36 UTC by SzymonGos

a few things left to add: 
- hamburger menu func,
- correct grid gaps

2022-06-02 11:41 UTC, korzewski requested changes

2022-06-02 11:41 UTC, korzewski commented on components/Navigation.tsx
> +        <ul className='flex md:col-start-8 md:order-3 lg:col-start-5 lg:col-span-8 flex-row lg:gap-x-12 text-gray-100 lg:order-2 justify-end items-center'>
Minor - classes order:
I would suggest to gave firstly col-span, col-start etc. because those ones describes the container of a component.

Later goes flex, flex-row and decorators like order, justify etc. 

At the end text colors, backgrounds, borders etc

2022-06-02 11:41 UTC, korzewski commented on components/Navigation.tsx
> +              <li key={i} className='hidden lg:block leading-[21.94px]'>
Usually you should round this value to fixed px - 22px.

In this case as those words wouldn't break you can use existing tailwind class leading-6, which is 24px. This shouldn't impact layout when they're centered vertically

2022-06-02 11:41 UTC, korzewski commented on pages/index.tsx
> +]
Please move this navigation to `Navigation` component directly instead of a prop. In this case we wouldn't get data from API's, so it's not necessary

2022-06-02 11:41 UTC, korzewski commented on components/buttons/SecondaryButton.tsx
> +      className='relative secondary-button-gradient font-space-grotesk font-bold text-[#FD0F9E] hover:text-white active:text-white rounded-2xl hover:bg-[linear-gradient(122.48deg,#671BC9_-52.99%,#FD0
You probably do not need relative here anymore?

2022-06-02 11:41 UTC, korzewski commented on components/Navigation.tsx
> +              <a href='#' className='relative z-10 md:py-3 md:px-8 lg:px-12 flex flex-1 items-center gap-x-[10px]'>
Not sure if you need z-index here?

2022-06-02 20:19 UTC, SzymonGos commented on components/DeployconttractsLogo.tsx
> +    <svg width='209' height='18' viewBox='0 0 209 18' fill='none' xmlns='http://www.w3.org/2000/svg' {...props}>
The logo changes its width and height depending on the screen.

2022-06-03 08:24 UTC, korzewski requested changes

2022-06-03 08:24 UTC, korzewski commented on components/NonOptimizedImage.tsx
> +  return <Image loader={({ src }) => src} unoptimized={true} {...props} />
Hmm cloudflare is still not picking up. Please use standard `<img />` tag here instead of Image from Next. Keep this component as we may find a better way to solve it in the future, then we would just fix it in one place

2022-06-03 08:24 UTC, korzewski commented on components/Navigation.tsx
> +    <nav className='p-5'>
When you add a horizontal spacing on grid as requested in a different PR, you would need to change this one to `py-5`. So you can do it now

2022-06-05 06:32 UTC, korzewski approved these changes

2022-06-05 09:01 UTC, merged