Intergate secret client
atomiklabs/deploycontracts.io pull request #53
Opened 2022-06-18 22:51 UTC by tk-o

2022-06-18 22:53 UTC, tk-o commented on components/snip-20/tokenSummary.tsx
> +          router.replace('/')
What do we want to do once token is created?

2022-06-18 22:54 UTC, tk-o commented on components/snip-20/tokenSummary.tsx
> +          console.error('something went wrong, try again')
Same question here - we need to provide an actionable hint to the user.

2022-06-18 22:55 UTC, tk-o commented on consts.ts
> +}
Todo: add validation to env vars hzod schema sounds good here)

2022-06-18 22:57 UTC, tk-o commented on lib/secret-client.ts
> +    } else {
This should be an elseif checking if a mnemonic was provided and then using it to create a signer instance.

2022-06-22 06:32 UTC, korzewski requested changes

2022-06-22 06:32 UTC, korzewski commented on lib/secret-client.ts
> +  const chainName = props.chainName
You can simplify this to
```
const {grpcUrl, rpcUrl ...} = props
```

2022-06-22 06:32 UTC, korzewski commented on lib/secret-client.ts
> +    throw Error('Wallet extension is not available. Install Keplr App and try again.')
This throw is outside try / catch in this function. Is it mistake, or expected behaviour for upper level catch?

2022-06-22 06:32 UTC, korzewski commented on components/snip-20/index.tsx
> +  }, [])
This use effect should happen when user clicks connect wallet button on tokenDetails page instead of generic page load

2022-06-22 06:32 UTC, korzewski commented on components/snip-20/tokenDetails.tsx
> +  )
This is one time use function, I'm not seeing much value of memoized useCallback here.
Would suggest simple 
```
async onConnectWallet() {
  const minterAddress = await connectWallet()
  setFieldValue('minterAddress', minterAddress))}
}
```

2022-06-22 06:35 UTC, korzewski commented on components/snip-20/tokenSummary.tsx
> +          router.replace('/')
I think we would redirect user to simple Congrats page, and there could be an info about JS implementation we would provide as Milestone 3 outcome. cc @deployAt

2022-06-22 06:38 UTC, korzewski commented on consts.ts
> +}
Could you please add a comment in the code?
So this won't be forgotten after merge
```
// TODO: add validation to env vars hzod schema sounds good here)
```

2022-06-22 06:39 UTC, korzewski commented on lib/secret-client.ts
> +    } else {
Could you please add code comment here?
```
// TODO: This should be an "else if" checking if a mnemonic was provided and then using it to create a signer instance
```

2022-06-26 09:53 UTC, tk-o commented on lib/secret-client.ts
> +    } else {
This is solved in [the related PR](https://github.com/atomiklabs/deploycontracts.io/pull/54/files#diff-25f3d34ef8743b98538aee8b4e93c5f146f20d9fdf220c2b39b3698da20e940dR91-R131) in the following way:

- the caller has to provide the signer, otherwise the client will be created in a read-only mode

2022-06-26 09:53 UTC, tk-o commented
Closing this PR. The changes have been refactored in a related one:
- https://github.com/atomiklabs/deploycontracts.io/pull/54

2022-06-26 09:53 UTC, closed without merging

2022-06-26 09:56 UTC, tk-o commented on components/snip-20/tokenSummary.tsx
> +  )
Nice share, I'll have a closer read and apply suggestions accordingly on #54

2022-06-26 09:59 UTC, tk-o commented on components/snip-20/index.tsx
> +  }, [])
There are two situation where calling `connectWallet` is required:

1. User interacts with a "Connect wallet" button
2. During the page load, assuming the user has interacted with "Connect wallet" button in previous sessions

This useEffect targets the 2nd use-case.

[Here](https://github.com/atomiklabs/deploycontracts.io/pull/54/files#diff-9b9123878dd0c073efbe2f8d095ab2457db37cf35edb8efc21494ae335eeb9a8R60-R75) is the complete implementation.

2022-06-26 10:00 UTC, tk-o commented on lib/secret-client.ts
> +    throw Error('Wallet extension is not available. Install Keplr App and try again.')
This is a library code, so it should leave the error handling to the app including it.

2022-06-26 10:01 UTC, tk-o commented on components/snip-20/tokenSummary.tsx
> +          router.replace('/')
This is done in #54